package citygrid;

public enum DrawingType {
	FOOD, TRAVEL, PROFESSIONAL, OFFICE, SHOP, OUTDOOR, ARTS, NIGHTLIFE, HOME, AIRPORT, COLLEGE, GYM, STADIUM, CLOTHING, GOVERNMENT, MUSEUM, MEDICAL, BUS, OTHER, NEUTRAL, NONE
}
