package citygrid;

import java.util.HashMap;


public class FsqNameHelper {
	public static final HashMap<String, String> CATEGORY_PARENTS = createCatParents();
	private static HashMap<String, String> createCatParents(){
		HashMap<String, String> catParents = new HashMap<String, String>();
		catParents.put("Arts & Entertainment", "Arts & Entertainment");
		catParents.put("Aquarium", "Arts & Entertainment");
		catParents.put("Arcade", "Arts & Entertainment");
		catParents.put("Art Gallery", "Arts & Entertainment");
		catParents.put("Bowling Alley", "Arts & Entertainment");
		catParents.put("Casino", "Arts & Entertainment");
		catParents.put("Comedy Club", "Arts & Entertainment");
		catParents.put("Concert Hall", "Arts & Entertainment");
		catParents.put("General Entertainment", "Arts & Entertainment");
		catParents.put("Historic Site", "Arts & Entertainment");
		catParents.put("Movie Theater", "Arts & Entertainment");
		catParents.put("Indie Movie Theater", "Arts & Entertainment");
		catParents.put("Multiplex", "Arts & Entertainment");
		catParents.put("Museum", "Arts & Entertainment");
		catParents.put("Art Museum", "Arts & Entertainment");
		catParents.put("History Museum", "Arts & Entertainment");
		catParents.put("Planetarium", "Arts & Entertainment");
		catParents.put("Science Museum", "Arts & Entertainment");
		catParents.put("Music Venue", "Arts & Entertainment");
		catParents.put("Jazz Club", "Arts & Entertainment");
		catParents.put("Piano Bar", "Arts & Entertainment");
		catParents.put("Rock Club", "Arts & Entertainment");
		catParents.put("Performing Arts Venue", "Arts & Entertainment");
		catParents.put("Dance Studio", "Arts & Entertainment");
		catParents.put("Indie Theater", "Arts & Entertainment");
		catParents.put("Opera House", "Arts & Entertainment");
		catParents.put("Theater", "Arts & Entertainment");
		catParents.put("Pool Hall", "Arts & Entertainment");
		catParents.put("Public Art", "Arts & Entertainment");
		catParents.put("Racetrack", "Arts & Entertainment");
		catParents.put("Stadium", "Arts & Entertainment");
		catParents.put("Baseball Stadium", "Arts & Entertainment");
		catParents.put("Basketball Stadium", "Arts & Entertainment");
		catParents.put("Cricket Ground", "Arts & Entertainment");
		catParents.put("Football Stadium", "Arts & Entertainment");
		catParents.put("Hockey Arena", "Arts & Entertainment");
		catParents.put("Soccer Stadium", "Arts & Entertainment");
		catParents.put("Tennis", "Arts & Entertainment");
		catParents.put("Track Stadium", "Arts & Entertainment");
		catParents.put("Theme Park", "Arts & Entertainment");
		catParents.put("Water Park", "Arts & Entertainment");
		catParents.put("Zoo", "Arts & Entertainment");
		catParents.put("College & University", "College & University");
		catParents.put("College Academic Building", "College & University");
		catParents.put("College Arts Building", "College & University");
		catParents.put("College Communications Building", "College & University");
		catParents.put("College Engineering Building", "College & University");
		catParents.put("College History Building", "College & University");
		catParents.put("College Math Building", "College & University");
		catParents.put("College Science Building", "College & University");
		catParents.put("College Technology Building", "College & University");
		catParents.put("College Administrative Building", "College & University");
		catParents.put("College Auditorium", "College & University");
		catParents.put("College Bookstore", "College & University");
		catParents.put("College Cafeteria", "College & University");
		catParents.put("College Classroom", "College & University");
		catParents.put("College Gym", "College & University");
		catParents.put("College Lab", "College & University");
		catParents.put("College Library", "College & University");
		catParents.put("College Quad", "College & University");
		catParents.put("College Rec Center", "College & University");
		catParents.put("College Residence Hall", "College & University");
		catParents.put("College Stadium", "College & University");
		catParents.put("College Baseball Diamond", "College & University");
		catParents.put("College Basketball Court", "College & University");
		catParents.put("College Cricket Pitch", "College & University");
		catParents.put("College Football Field", "College & University");
		catParents.put("College Hockey Rink", "College & University");
		catParents.put("College Soccer Field", "College & University");
		catParents.put("College Tennis Court", "College & University");
		catParents.put("College Track", "College & University");
		catParents.put("College Theater", "College & University");
		catParents.put("Community College", "College & University");
		catParents.put("Fraternity House", "College & University");
		catParents.put("General College & University", "College & University");
		catParents.put("Law School", "College & University");
		catParents.put("Medical School", "College & University");
		catParents.put("Sorority House", "College & University");
		catParents.put("Student Center", "College & University");
		catParents.put("Trade School", "College & University");
		catParents.put("University", "College & University");
		catParents.put("Food", "Food");
		catParents.put("Afghan Restaurant", "Food");
		catParents.put("African Restaurant", "Food");
		catParents.put("American Restaurant", "Food");
		catParents.put("Arepa Restaurant", "Food");
		catParents.put("Argentinian Restaurant", "Food");
		catParents.put("Asian Restaurant", "Food");
		catParents.put("Australian Restaurant", "Food");
		catParents.put("BBQ Joint", "Food");
		catParents.put("Bagel Shop", "Food");
		catParents.put("Bakery", "Food");
		catParents.put("Brazilian Restaurant", "Food");
		catParents.put("Breakfast Spot", "Food");
		catParents.put("Brewery", "Food");
		catParents.put("Burger Joint", "Food");
		catParents.put("Burrito Place", "Food");
		catParents.put("Café", "Food");
		catParents.put("Cajun / Creole Restaurant", "Food");
		catParents.put("Caribbean Restaurant", "Food");
		catParents.put("Chinese Restaurant", "Food");
		catParents.put("Coffee Shop", "Food");
		catParents.put("Cuban Restaurant", "Food");
		catParents.put("Cupcake Shop", "Food");
		catParents.put("Deli / Bodega", "Food");
		catParents.put("Dessert Shop", "Food");
		catParents.put("Dim Sum Restaurant", "Food");
		catParents.put("Diner", "Food");
		catParents.put("Distillery", "Food");
		catParents.put("Donut Shop", "Food");
		catParents.put("Dumpling Restaurant", "Food");
		catParents.put("Eastern European Restaurant", "Food");
		catParents.put("Ethiopian Restaurant", "Food");
		catParents.put("Falafel Restaurant", "Food");
		catParents.put("Fast Food Restaurant", "Food");
		catParents.put("Filipino Restaurant", "Food");
		catParents.put("Fish & Chips Shop", "Food");
		catParents.put("Food Truck", "Food");
		catParents.put("French Restaurant", "Food");
		catParents.put("Fried Chicken Joint", "Food");
		catParents.put("Gastropub", "Food");
		catParents.put("German Restaurant", "Food");
		catParents.put("Gluten-free Restaurant", "Food");
		catParents.put("Greek Restaurant", "Food");
		catParents.put("Hot Dog Joint", "Food");
		catParents.put("Ice Cream Shop", "Food");
		catParents.put("Indian Restaurant", "Food");
		catParents.put("Indonesian Restaurant", "Food");
		catParents.put("Italian Restaurant", "Food");
		catParents.put("Japanese Restaurant", "Food");
		catParents.put("Juice Bar", "Food");
		catParents.put("Korean Restaurant", "Food");
		catParents.put("Latin American Restaurant", "Food");
		catParents.put("Mac & Cheese Joint", "Food");
		catParents.put("Malaysian Restaurant", "Food");
		catParents.put("Mediterranean Restaurant", "Food");
		catParents.put("Mexican Restaurant", "Food");
		catParents.put("Middle Eastern Restaurant", "Food");
		catParents.put("Molecular Gastronomy Restaurant", "Food");
		catParents.put("Mongolian Restaurant", "Food");
		catParents.put("Moroccan Restaurant", "Food");
		catParents.put("New American Restaurant", "Food");
		catParents.put("Peruvian Restaurant", "Food");
		catParents.put("Pizza Place", "Food");
		catParents.put("Portuguese Restaurant", "Food");
		catParents.put("Ramen /  Noodle House", "Food");
		catParents.put("Restaurant", "Food");
		catParents.put("Salad Place", "Food");
		catParents.put("Sandwich Place", "Food");
		catParents.put("Scandinavian Restaurant", "Food");
		catParents.put("Seafood Restaurant", "Food");
		catParents.put("Snack Place", "Food");
		catParents.put("Soup Place", "Food");
		catParents.put("South American Restaurant", "Food");
		catParents.put("Southern / Soul Food Restaurant", "Food");
		catParents.put("Spanish Restaurant", "Food");
		catParents.put("Paella Restaurant", "Food");
		catParents.put("Steakhouse", "Food");
		catParents.put("Sushi Restaurant", "Food");
		catParents.put("Swiss Restaurant", "Food");
		catParents.put("Taco Place", "Food");
		catParents.put("Tapas Restaurant", "Food");
		catParents.put("Tea Room", "Food");
		catParents.put("Thai Restaurant", "Food");
		catParents.put("Turkish Restaurant", "Food");
		catParents.put("Vegetarian / Vegan Restaurant", "Food");
		catParents.put("Vietnamese Restaurant", "Food");
		catParents.put("Winery", "Food");
		catParents.put("Wings Joint", "Food");
		catParents.put("Nightlife Spot", "Nightlife Spot");
		catParents.put("Bar", "Nightlife Spot");
		catParents.put("Beer Garden", "Nightlife Spot");
		catParents.put("Cocktail Bar", "Nightlife Spot");
		catParents.put("Dive Bar", "Nightlife Spot");
		catParents.put("Gay Bar", "Nightlife Spot");
		catParents.put("Hookah Bar", "Nightlife Spot");
		catParents.put("Hotel Bar", "Nightlife Spot");
		catParents.put("Karaoke Bar", "Nightlife Spot");
		catParents.put("Lounge", "Nightlife Spot");
		catParents.put("Nightclub", "Nightlife Spot");
		catParents.put("Other Nightlife", "Nightlife Spot");
		catParents.put("Pub", "Nightlife Spot");
		catParents.put("Sake Bar", "Nightlife Spot");
		catParents.put("Speakeasy", "Nightlife Spot");
		catParents.put("Sports Bar", "Nightlife Spot");
		catParents.put("Strip Club", "Nightlife Spot");
		catParents.put("Whisky Bar", "Nightlife Spot");
		catParents.put("Wine Bar", "Nightlife Spot");
		catParents.put("Outdoors & Recreation", "Outdoors & Recreation");
		catParents.put("Athletic & Sport", "Outdoors & Recreation");
		catParents.put("Baseball Field", "Outdoors & Recreation");
		catParents.put("Basketball Court", "Outdoors & Recreation");
		catParents.put("Golf Course", "Outdoors & Recreation");
		catParents.put("Hockey Field", "Outdoors & Recreation");
		catParents.put("Paintball Field", "Outdoors & Recreation");
		catParents.put("Skate Park", "Outdoors & Recreation");
		catParents.put("Skating Rink", "Outdoors & Recreation");
		catParents.put("Soccer Field", "Outdoors & Recreation");
		catParents.put("Tennis Court", "Outdoors & Recreation");
		catParents.put("Volleyball Court", "Outdoors & Recreation");
		catParents.put("Beach", "Outdoors & Recreation");
		catParents.put("Surf Spot", "Outdoors & Recreation");
		catParents.put("Bridge", "Outdoors & Recreation");
		catParents.put("Campground", "Outdoors & Recreation");
		catParents.put("Cemetery", "Outdoors & Recreation");
		catParents.put("Dog Run", "Outdoors & Recreation");
		catParents.put("Farm", "Outdoors & Recreation");
		catParents.put("Field", "Outdoors & Recreation");
		catParents.put("Garden", "Outdoors & Recreation");
		catParents.put("Harbor / Marina", "Outdoors & Recreation");
		catParents.put("Hiking Trail", "Outdoors & Recreation");
		catParents.put("Hot Spring", "Outdoors & Recreation");
		catParents.put("Lake", "Outdoors & Recreation");
		catParents.put("Lighthouse", "Outdoors & Recreation");
		catParents.put("Mountain", "Outdoors & Recreation");
		catParents.put("Neighborhood", "Outdoors & Recreation");
		catParents.put("Other Great Outdoors", "Outdoors & Recreation");
		catParents.put("Park", "Outdoors & Recreation");
		catParents.put("Playground", "Outdoors & Recreation");
		catParents.put("Plaza", "Outdoors & Recreation");
		catParents.put("Pool", "Outdoors & Recreation");
		catParents.put("River", "Outdoors & Recreation");
		catParents.put("Rock Climbing Spot", "Outdoors & Recreation");
		catParents.put("Scenic Lookout", "Outdoors & Recreation");
		catParents.put("Sculpture Garden", "Outdoors & Recreation");
		catParents.put("Ski Area", "Outdoors & Recreation");
		catParents.put("Apres Ski Bar", "Outdoors & Recreation");
		catParents.put("Ski Chairlift", "Outdoors & Recreation");
		catParents.put("Ski Chalet", "Outdoors & Recreation");
		catParents.put("Ski Lodge", "Outdoors & Recreation");
		catParents.put("Ski Trail", "Outdoors & Recreation");
		catParents.put("Stable", "Outdoors & Recreation");
		catParents.put("Vineyard", "Outdoors & Recreation");
		catParents.put("Volcano", "Outdoors & Recreation");
		catParents.put("Well", "Outdoors & Recreation");
		catParents.put("Professional & Other Places", "Professional & Other Places");
		catParents.put("Animal Shelter", "Professional & Other Places");
		catParents.put("Auditorium", "Professional & Other Places");
		catParents.put("Building", "Professional & Other Places");
		catParents.put("Convention Center", "Professional & Other Places");
		catParents.put("Meeting Room", "Professional & Other Places");
		catParents.put("Event Space", "Professional & Other Places");
		catParents.put("Factory", "Professional & Other Places");
		catParents.put("Fair", "Professional & Other Places");
		catParents.put("Funeral Home", "Professional & Other Places");
		catParents.put("Government Building", "Professional & Other Places");
		catParents.put("Capitol Building", "Professional & Other Places");
		catParents.put("City Hall", "Professional & Other Places");
		catParents.put("Courthouse", "Professional & Other Places");
		catParents.put("Fire Station", "Professional & Other Places");
		catParents.put("Monument / Landmark", "Professional & Other Places");
		catParents.put("Police Station", "Professional & Other Places");
		catParents.put("Library", "Professional & Other Places");
		catParents.put("Medical Center", "Professional & Other Places");
		catParents.put("Dentist's Office", "Professional & Other Places");
		catParents.put("Doctor's Office", "Professional & Other Places");
		catParents.put("Emergency Room", "Professional & Other Places");
		catParents.put("Hospital", "Professional & Other Places");
		catParents.put("Laboratory", "Professional & Other Places");
		catParents.put("Optical Shop", "Professional & Other Places");
		catParents.put("Veterinarian", "Professional & Other Places");
		catParents.put("Military Base", "Professional & Other Places");
		catParents.put("Non-Profit", "Professional & Other Places");
		catParents.put("Office", "Professional & Other Places");
		catParents.put("Cafeteria", "Professional & Other Places");
		catParents.put("Campaign Office", "Professional & Other Places");
		catParents.put("Conference Room", "Professional & Other Places");
		catParents.put("Coworking Space", "Professional & Other Places");
		catParents.put("Tech Startup", "Professional & Other Places");
		catParents.put("Parking", "Professional & Other Places");
		catParents.put("Post Office", "Professional & Other Places");
		catParents.put("Radio Station", "Professional & Other Places");
		catParents.put("School", "Professional & Other Places");
		catParents.put("Elementary School", "Professional & Other Places");
		catParents.put("High School", "Professional & Other Places");
		catParents.put("Middle School", "Professional & Other Places");
		catParents.put("Music School", "Professional & Other Places");
		catParents.put("Nursery School", "Professional & Other Places");
		catParents.put("Spiritual Center", "Professional & Other Places");
		catParents.put("Church", "Professional & Other Places");
		catParents.put("Mosque", "Professional & Other Places");
		catParents.put("Shrine", "Professional & Other Places");
		catParents.put("Synagogue", "Professional & Other Places");
		catParents.put("Temple", "Professional & Other Places");
		catParents.put("Voting Booth", "Professional & Other Places");
		catParents.put("Residence", "Residence");
		catParents.put("Assisted Living", "Residence");
		catParents.put("Home (private)", "Residence");
		catParents.put("Housing Development", "Residence");
		catParents.put("Residential Building (Apartment / Condo)", "Residence");
		catParents.put("Shop & Service", "Shop & Service");
		catParents.put("Antique Shop", "Shop & Service");
		catParents.put("Arts & Crafts Store", "Shop & Service");
		catParents.put("Automotive Shop", "Shop & Service");
		catParents.put("Bank", "Shop & Service");
		catParents.put("Bike Shop", "Shop & Service");
		catParents.put("Board Shop", "Shop & Service");
		catParents.put("Bookstore", "Shop & Service");
		catParents.put("Bridal Shop", "Shop & Service");
		catParents.put("Camera Store", "Shop & Service");
		catParents.put("Candy Store", "Shop & Service");
		catParents.put("Car Dealership", "Shop & Service");
		catParents.put("Car Wash", "Shop & Service");
		catParents.put("Clothing Store", "Shop & Service");
		catParents.put("Accessories Store", "Shop & Service");
		catParents.put("Boutique", "Shop & Service");
		catParents.put("Kids Store", "Shop & Service");
		catParents.put("Lingerie Store", "Shop & Service");
		catParents.put("Men's Store", "Shop & Service");
		catParents.put("Shoe Store", "Shop & Service");
		catParents.put("Women's Store", "Shop & Service");
		catParents.put("Convenience Store", "Shop & Service");
		catParents.put("Cosmetics Shop", "Shop & Service");
		catParents.put("Credit Union", "Shop & Service");
		catParents.put("Daycare", "Shop & Service");
		catParents.put("Department Store", "Shop & Service");
		catParents.put("Design Studio", "Shop & Service");
		catParents.put("Drugstore / Pharmacy", "Shop & Service");
		catParents.put("EV Charging Station", "Shop & Service");
		catParents.put("Electronics Store", "Shop & Service");
		catParents.put("Financial or Legal Service", "Shop & Service");
		catParents.put("Flea Market", "Shop & Service");
		catParents.put("Flower Shop", "Shop & Service");
		catParents.put("Food & Drink Shop", "Shop & Service");
		catParents.put("Butcher", "Shop & Service");
		catParents.put("Cheese Shop", "Shop & Service");
		catParents.put("Farmers Market", "Shop & Service");
		catParents.put("Fish Market", "Shop & Service");
		catParents.put("Food Court", "Shop & Service");
		catParents.put("Gourmet Shop", "Shop & Service");
		catParents.put("Grocery Store", "Shop & Service");
		catParents.put("Liquor Store", "Shop & Service");
		catParents.put("Wine Shop", "Shop & Service");
		catParents.put("Furniture / Home Store", "Shop & Service");
		catParents.put("Gaming Cafe", "Shop & Service");
		catParents.put("Garden Center", "Shop & Service");
		catParents.put("Gas Station / Garage", "Shop & Service");
		catParents.put("Gift Shop", "Shop & Service");
		catParents.put("Gym / Fitness Center", "Shop & Service");
		catParents.put("Climbing Gym", "Shop & Service");
		catParents.put("Gym Pool", "Shop & Service");
		catParents.put("Gym", "Shop & Service");
		catParents.put("Martial Arts Dojo", "Shop & Service");
		catParents.put("Track", "Shop & Service");
		catParents.put("Yoga Studio", "Shop & Service");
		catParents.put("Hardware Store", "Shop & Service");
		catParents.put("Hobby Shop", "Shop & Service");
		catParents.put("Internet Cafe", "Shop & Service");
		catParents.put("Jewelry Store", "Shop & Service");
		catParents.put("Laundry Service", "Shop & Service");
		catParents.put("Mall", "Shop & Service");
		catParents.put("Miscellaneous Shop", "Shop & Service");
		catParents.put("Mobile Phone Shop", "Shop & Service");
		catParents.put("Motorcycle Shop", "Shop & Service");
		catParents.put("Music Store", "Shop & Service");
		catParents.put("Nail Salon", "Shop & Service");
		catParents.put("Newsstand", "Shop & Service");
		catParents.put("Paper / Office Supplies Store", "Shop & Service");
		catParents.put("Pet Service", "Shop & Service");
		catParents.put("Pet Store", "Shop & Service");
		catParents.put("Photography Lab", "Shop & Service");
		catParents.put("Real Estate Office", "Shop & Service");
		catParents.put("Record Shop", "Shop & Service");
		catParents.put("Recycling Facility", "Shop & Service");
		catParents.put("Salon / Barbershop", "Shop & Service");
		catParents.put("Smoke Shop", "Shop & Service");
		catParents.put("Spa / Massage", "Shop & Service");
		catParents.put("Sporting Goods Shop", "Shop & Service");
		catParents.put("Storage Facility", "Shop & Service");
		catParents.put("Tailor Shop", "Shop & Service");
		catParents.put("Tanning Salon", "Shop & Service");
		catParents.put("Tattoo Parlor", "Shop & Service");
		catParents.put("Thrift / Vintage Store", "Shop & Service");
		catParents.put("Toy / Game Store", "Shop & Service");
		catParents.put("Travel Agency", "Shop & Service");
		catParents.put("Video Game Store", "Shop & Service");
		catParents.put("Video Store", "Shop & Service");
		catParents.put("Travel & Transport", "Travel & Transport");
		catParents.put("Airport", "Travel & Transport");
		catParents.put("Airport Food Court", "Travel & Transport");
		catParents.put("Airport Gate", "Travel & Transport");
		catParents.put("Airport Lounge", "Travel & Transport");
		catParents.put("Airport Terminal", "Travel & Transport");
		catParents.put("Airport Tram", "Travel & Transport");
		catParents.put("Plane", "Travel & Transport");
		catParents.put("Bike Rental / Bike Share", "Travel & Transport");
		catParents.put("Bus Station", "Travel & Transport");
		catParents.put("Bus Line", "Travel & Transport");
		catParents.put("Embassy / Consulate", "Travel & Transport");
		catParents.put("Ferry", "Travel & Transport");
		catParents.put("Boat or Ferry", "Travel & Transport");
		catParents.put("Pier", "Travel & Transport");
		catParents.put("General Travel", "Travel & Transport");
		catParents.put("Hotel", "Travel & Transport");
		catParents.put("Bed & Breakfast", "Travel & Transport");
		catParents.put("Boarding House", "Travel & Transport");
		catParents.put("Hostel", "Travel & Transport");
		catParents.put("Hotel Pool", "Travel & Transport");
		catParents.put("Motel", "Travel & Transport");
		catParents.put("Resort", "Travel & Transport");
		catParents.put("Roof Deck", "Travel & Transport");
		catParents.put("Light Rail", "Travel & Transport");
		catParents.put("Moving Target", "Travel & Transport");
		catParents.put("Rental Car Location", "Travel & Transport");
		catParents.put("Rest Area", "Travel & Transport");
		catParents.put("Road", "Travel & Transport");
		catParents.put("Subway", "Travel & Transport");
		catParents.put("Taxi", "Travel & Transport");
		catParents.put("Tourist Information Center", "Travel & Transport");
		catParents.put("Train Station", "Travel & Transport");
		catParents.put("Platform", "Travel & Transport");
		catParents.put("Train", "Travel & Transport");
		catParents.put("Travel Lounge", "Travel & Transport");
		return catParents;
	}
}
