package citygrid;

import java.io.File;
import java.util.HashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import processing.core.PApplet;
import processing.core.PGraphics;
import processing.core.PImage;
import processing.core.PVector;
import toxi.color.TColor;

public class PatternDrawManager {
	Pattern pattern = Pattern.compile("\\s+|\\/|&|\\(|\\)|'");
	
	HashMap<String, TColor> iconColors = new HashMap<String, TColor>();
	HashMap<String, String> categoryParents = new HashMap<String, String>();
	
	File file = new File("data/fsq_icons");
	File[] files = file.listFiles();
	HashMap<String, String> iconPaths = new HashMap<String, String>();
	public PatternDrawManager(){
		for (int i = 0; i < files.length; i++) {
			String[] splitted = files[i].getPath().split("/"); 
			String filename = splitted[splitted.length-1].split("\\.")[0];
			iconPaths.put(filename, files[i].getPath());
	    }
		createCategoryParents();
		createColors();
	}
	
	public PImage createPattern(String catName, int sizeX, int sizeY,  PVector[] maskShape, int tileSize){
		String name = convertCatNameToFileName(catName);
		String path = iconPaths.get(name);
		PImage tile = CityGrid.p5.loadImage(path);
		tile.resize(tileSize, tileSize);
		int tilesX = (int)Math.ceil(sizeX/(float)tile.width);
		int tilesY = (int)Math.ceil(sizeY/(float)tile.height);
		PGraphics mask = CityGrid.p5.createGraphics(tilesX*tile.width, tilesY*tile.height, PApplet.JAVA2D);
		mask.beginDraw();
		mask.background(0);
		mask.fill(255);
		mask.beginShape();
		for (int i = 0; i < maskShape.length; i++) {
			mask.vertex(maskShape[i].x,maskShape[i].y);
		}
		mask.endShape();
		mask.endDraw();
		PImage piMask = mask.get(0, 0, mask.width, mask.height);
		
		PGraphics pattern = CityGrid.p5.createGraphics(tilesX*tile.width, tilesY*tile.height, PApplet.JAVA2D);
		pattern.beginDraw();
		TColor c = new TColor(iconColors.get(categoryParents.get(catName)));
		pattern.background(c.toARGB());
		pattern.smooth();
		pattern.tint(c.lighten(0.3f).toARGB());
		for (int i = 0; i < tilesX; i++) {
			for (int j = 0; j < tilesY; j++) {
				pattern.image(tile,tile.width*i,tile.height*j);	
			}	
		}
//		pattern.stroke(0,0,255);
//		pattern.strokeWeight(2);
//		pattern.noFill();
//		pattern.beginShape();
//		for (int i = 0; i < maskShape.length; i++) {
//			pattern.vertex(maskShape[i].x,maskShape[i].y);
//		}
//		pattern.endShape();
		pattern.endDraw();
		PImage piPattern = pattern.get();
		piPattern.mask(piMask);
		return piPattern;
	}
	
	private String convertCatNameToFileName(String catName){
		Matcher matcher = pattern.matcher(catName);
		StringBuffer sb = new StringBuffer();
		while (matcher.find()) {
		     matcher.appendReplacement(sb, "");
		    // s now contains "BAR"
		}
		matcher.appendTail(sb);
		System.out.println(this.getClass().getName()+": "+sb.toString());
		return sb.toString();
	}
	
	private void createColors(){
		TColor c_default = TColor.newRGBA(1,0,0,1);
		
		iconColors.put("Arts & Entertainment", TColor.newHex("854237"));
		iconColors.put("College & University", TColor.newHex("7F4156"));
		iconColors.put("Food", TColor.newHex("614D6D"));
		iconColors.put("Nightlife Spot", TColor.newHex("315870"));
		iconColors.put("Outdoors & Recreation", TColor.newHex("335772"));
		iconColors.put("Professional & Other Places", TColor.newHex("235D3D"));
		iconColors.put("Residence", TColor.newHex("485821"));
		iconColors.put("Shop & Service", TColor.newHex("684E1A"));
		iconColors.put("Travel & Transport", TColor.newHex("7C412C"));
		
		
		
		
		
		
//		iconColors.put("Plaza",c_default);
//		iconColors.put("Bus Station",c_default);
//		iconColors.put("Hotel",c_default);
//		iconColors.put("Bed & Breakfast",c_default);
//		iconColors.put("Home (private)",c_default);
//		iconColors.put("Playground",c_default);
//		iconColors.put("Hockey Arena",c_default);
//		iconColors.put("Gay Bar",c_default);
//		iconColors.put("Bar",c_default);
//		iconColors.put("Tech Startup",c_default);
//		iconColors.put("Historic Site",c_default);
//		iconColors.put("History Museum",c_default);
//		iconColors.put("Field",c_default);
//		iconColors.put("Park",c_default);
//		iconColors.put("Beach",c_default);
//		iconColors.put("Flea Market",c_default);
//		iconColors.put("Karaoke Bar",c_default);
//		iconColors.put("Mall",c_default);
//		iconColors.put("Train Station",c_default);
//		iconColors.put("Concert Hall",c_default);
//		iconColors.put("Airport",c_default);
//		iconColors.put("Hospital",c_default);
//		iconColors.put("Platform",c_default);
//		iconColors.put("Airport Gate",c_default);
//		iconColors.put("Subway",c_default);
//		iconColors.put("University",c_default);
//		iconColors.put("Café",c_default);
//		iconColors.put("Office",c_default);
//		iconColors.put("Event Space",c_default);
//		iconColors.put("Bank",c_default);
//		iconColors.put("Dentist's Office",c_default);
//		iconColors.put("French Restaurant",c_default);
//		iconColors.put("BBQ Joint",c_default);
//		iconColors.put("Convention Center",c_default);
//		iconColors.put("Deli / Bodega",c_default);
//		iconColors.put("Monument / Landmark",c_default);
//		iconColors.put("Clothing Store",c_default);
//		iconColors.put("Bus Line",c_default);
//		iconColors.put("Golf Course",c_default);
//		iconColors.put("Grocery Store",c_default);
//		iconColors.put("Light Rail",c_default);
//		iconColors.put("General Entertainment",c_default);
//		iconColors.put("Fast Food Restaurant",c_default);
//		iconColors.put("Scenic Lookout",c_default);
//		iconColors.put("Burger Joint",c_default);
//		iconColors.put("Italian Restaurant",c_default);
//		iconColors.put("Mexican Restaurant",c_default);
//		iconColors.put("Residential Building (Apartment / Condo)",c_default);
//		iconColors.put("Bridge",c_default);
//		iconColors.put("Neighborhood",c_default);
//		iconColors.put("Movie Theater",c_default);
//		iconColors.put("Asian Restaurant",c_default);
//		iconColors.put("Newsstand",c_default);
//		iconColors.put("Church",c_default);
//		iconColors.put("River",c_default);
//		iconColors.put("General Travel",c_default);
//		iconColors.put("Nightclub",c_default);
//		iconColors.put("Farmers Market",c_default);
//		iconColors.put("Vietnamese Restaurant",c_default);
//		iconColors.put("German Restaurant",c_default);
//		iconColors.put("Electronics Store",c_default);
//		iconColors.put("Other Great Outdoors",c_default);
//		iconColors.put("Boutique",c_default);
//		iconColors.put("Restaurant",c_default);
//		iconColors.put("Rock Club",c_default);
//		iconColors.put("Government Building",c_default);
//		iconColors.put("Moving Target",c_default);
//		iconColors.put("Japanese Restaurant",c_default);
//		iconColors.put("Art Museum",c_default);
//		iconColors.put("Diner",c_default);
//		iconColors.put("Tanning Salon",c_default);
//		iconColors.put("Turkish Restaurant",c_default);
//		iconColors.put("Building",c_default);
//		iconColors.put("Gas Station / Garage",c_default);
//		iconColors.put("College Academic Building",c_default);
//		iconColors.put("Miscellaneous Shop",c_default);
//		iconColors.put("Doctor's Office",c_default);
//		iconColors.put("Airport Terminal",c_default);
//		iconColors.put("Coworking Space",c_default);
//		iconColors.put("College Lab",c_default);
//		iconColors.put("Sushi Restaurant",c_default);
//		iconColors.put("Stable",c_default);
//		iconColors.put("Music Venue",c_default);
//		iconColors.put("College & University",c_default);
//		iconColors.put("School",c_default);
//		iconColors.put("Dive Bar",c_default);
//		iconColors.put("Hotel Bar",c_default);
//		iconColors.put("Coffee Shop",c_default);
//		iconColors.put("Mediterranean Restaurant",c_default);
//		iconColors.put("Courthouse",c_default);
//		iconColors.put("Farm",c_default);
//		iconColors.put("Strip Club",c_default);
//		iconColors.put("Furniture / Home Store",c_default);
//		iconColors.put("Gym",c_default);
//		iconColors.put("Pub",c_default);
//		iconColors.put("Lounge",c_default);
//		iconColors.put("Performing Arts Venue",c_default);
//		iconColors.put("Hostel",c_default);
//		iconColors.put("Steakhouse",c_default);
//		iconColors.put("General College & University",c_default);
//		iconColors.put("Pizza Place",c_default);
//		iconColors.put("Snack Place",c_default);
//		iconColors.put("City Hall",c_default);
//		iconColors.put("Military Base",c_default);
//		iconColors.put("Breakfast Spot",c_default);
//		iconColors.put("Motel",c_default);
//		iconColors.put("Cafeteria",c_default);
//		iconColors.put("Museum",c_default);
//		iconColors.put("College Library",c_default);
//		iconColors.put("Arcade",c_default);
//		iconColors.put("Hardware Store",c_default);
//		iconColors.put("Bakery",c_default);
//		iconColors.put("Stadium",c_default);
//		iconColors.put("Department Store",c_default);
//		iconColors.put("Housing Development",c_default);
//		iconColors.put("Capitol Building",c_default);
//		iconColors.put("Indie Movie Theater",c_default);
//		iconColors.put("Cocktail Bar",c_default);
//		iconColors.put("Garden",c_default);
//		iconColors.put("Travel Lounge",c_default);
//		iconColors.put("Butcher",c_default);
//		iconColors.put("Fire Station",c_default);
//		iconColors.put("Train",c_default);
//		iconColors.put("Food & Drink Shop",c_default);
//		iconColors.put("Drugstore / Pharmacy",c_default);
//		iconColors.put("Automotive Shop",c_default);
//		iconColors.put("Resort",c_default);
//		iconColors.put("American Restaurant",c_default);
//		iconColors.put("Sandwich Place",c_default);
//		iconColors.put("Brewery",c_default);
//		iconColors.put("Theater",c_default);
//		iconColors.put("Middle Eastern Restaurant",c_default);
//		iconColors.put("Art Gallery",c_default);
//		iconColors.put("Beer Garden",c_default);
//		iconColors.put("College Classroom",c_default);
//		iconColors.put("Zoo",c_default);
//		iconColors.put("Car Wash",c_default);
//		iconColors.put("Boat or Ferry",c_default);
//		iconColors.put("Arepa Restaurant",c_default);
//		iconColors.put("Indian Restaurant",c_default);
//		iconColors.put("Spa / Massage",c_default);
//		iconColors.put("Post Office",c_default);
//		iconColors.put("Chinese Restaurant", c_default);
//		iconColors.put("New American Restaurant",c_default);
//		iconColors.put("Jazz Club", c_default);
//		iconColors.put("Bowling Alley", c_default);
//		iconColors.put("Food Truck", c_default);
//		iconColors.put("Hot Dog Joint", c_default);
//		iconColors.put("Road", c_default);
//		iconColors.put("Tennis", c_default);
//		iconColors.put("Women's Store", c_default);
//		iconColors.put("Greek Restaurant", c_default);
//		iconColors.put("Thai Restaurant", c_default);
//		iconColors.put("Caribbean Restaurant", c_default);
//		iconColors.put("Latin American Restaurant", c_default);
//		iconColors.put("Surf Spot", c_default);
//		iconColors.put("Sports Bar", c_default);
//		iconColors.put("Hookah Bar", c_default);
//		iconColors.put("Track", c_default);
//		iconColors.put("Racetrack", c_default);
//		iconColors.put("Professional & Other Places", c_default);
//		iconColors.put("Pool", c_default);
//		iconColors.put("Dog Run", c_default);
//		iconColors.put("Harbor / Marina", c_default);
//		iconColors.put("Donut Shop", c_default);
//		iconColors.put("Airport Tram", c_default);
//		iconColors.put("College Residence Hall", c_default);
//		iconColors.put("Gym / Fitness Center", c_default);
//		iconColors.put("Salon / Barbershop", c_default);
//		iconColors.put("Medical Center", c_default);
//		iconColors.put("Multiplex", c_default);
//		iconColors.put("Bagel Shop", c_default);
//		iconColors.put("Ice Cream Shop", c_default);
//		iconColors.put("Dessert Shop", c_default);
//		iconColors.put("Car Dealership", c_default);
//		iconColors.put("Arts & Entertainment", c_default);
//		iconColors.put("Toy / Game Store", c_default);
//		iconColors.put("Football Stadium", c_default);
//		iconColors.put("Mobile Phone Shop", c_default);
//		iconColors.put("Baseball Field", c_default);
//		iconColors.put("Athletic & Sport", c_default);
//		iconColors.put("Shoe Store", c_default);
//		iconColors.put("Southern / Soul Food Restaurant", c_default);
//		iconColors.put("Brazilian Restaurant", c_default);
//		iconColors.put("Korean Restaurant", c_default);
//		iconColors.put("Peruvian Restaurant", c_default);
//		iconColors.put("Falafel Restaurant", c_default);
//		iconColors.put("Cuban Restaurant", c_default);
//		iconColors.put("Fried Chicken Joint", c_default);
//		iconColors.put("Taco Place", c_default);
//		iconColors.put("Ramen /  Noodle House", c_default);
//		iconColors.put("Speakeasy", c_default);
//		iconColors.put("Outdoors & Recreation", c_default);
//		iconColors.put("Laundry Service", c_default);
//		iconColors.put("Gastropub", c_default);
//		iconColors.put("Theme Park", c_default);
//		iconColors.put("Record Shop", c_default);
//		iconColors.put("Campground", c_default);
//		iconColors.put("Other Nightlife", c_default);
//		iconColors.put("Video Store", c_default);
//		iconColors.put("Rental Car Location", c_default);
//		iconColors.put("Hiking Trail", c_default);
//		iconColors.put("Basketball Stadium", c_default);
//		iconColors.put("Ski Chalet", c_default);
//		iconColors.put("Ski Area", c_default);
//		iconColors.put("Liquor Store", c_default);
//		iconColors.put("Baseball Stadium", c_default);
//		iconColors.put("Wine Bar", c_default);
//		iconColors.put("Voting Booth", c_default);
//		iconColors.put("Fraternity House", c_default);
//		iconColors.put("Sculpture Garden", c_default);
//		iconColors.put("Pier", c_default);
//		iconColors.put("College Technology Building", c_default);
//		iconColors.put("Design Studio", c_default);
//		iconColors.put("Emergency Room", c_default);
//		iconColors.put("Martial Arts Dojo", c_default);
//		iconColors.put("Jewelry Store", c_default);
//		iconColors.put("Men's Store", c_default);
//		iconColors.put("Tennis Court", c_default);
//		iconColors.put("Vegetarian / Vegan Restaurant", c_default);
//		iconColors.put("Moroccan Restaurant", c_default);
//		iconColors.put("Eastern European Restaurant", c_default);
//		iconColors.put("Argentinian Restaurant", c_default);
//		iconColors.put("Tapas Restaurant", c_default);
//		iconColors.put("Whisky Bar", c_default);
//		iconColors.put("Airport Lounge", c_default);
//		iconColors.put("Police Station", c_default);
//		iconColors.put("Candy Store", c_default);
//		iconColors.put("Shop & Service", c_default);
//		iconColors.put("Parking", c_default);
//		iconColors.put("Gym Pool", c_default);
//		iconColors.put("Soccer Stadium", c_default);
//		iconColors.put("Science Museum", c_default);
//		iconColors.put("Sporting Goods Shop", c_default);
//		iconColors.put("Cemetery", c_default);
//		iconColors.put("Dance Studio", c_default);
//		iconColors.put("Cupcake Shop", c_default);
//		iconColors.put("Cosmetics Shop", c_default);
//		iconColors.put("Casino", c_default);
//		iconColors.put("Lake", c_default);
//		iconColors.put("Nursery School", c_default);
//		iconColors.put("College Basketball Court", c_default);
//		iconColors.put("Tea Room", c_default);
//		iconColors.put("Temple", c_default);
//		iconColors.put("Internet Cafe", c_default);
//		iconColors.put("Soccer Field", c_default);
//		iconColors.put("Skate Park", c_default);
//		iconColors.put("Meeting Room", c_default);
//		iconColors.put("Residence", c_default);
//		iconColors.put("Camera Store", c_default);
//		iconColors.put("High School", c_default);
//		iconColors.put("Nail Salon", c_default);
//		iconColors.put("Accessories Store", c_default);
//		iconColors.put("Tattoo Parlor", c_default);
//		iconColors.put("Bookstore", c_default);
//		iconColors.put("Yoga Studio", c_default);
//		iconColors.put("Opera House", c_default);
//		iconColors.put("Conference Room", c_default);
//		iconColors.put("Library", c_default);
//		iconColors.put("Student Center", c_default);
//		iconColors.put("Gourmet Shop", c_default);
//		iconColors.put("Comedy Club", c_default);
//		iconColors.put("Flower Shop", c_default);
//		iconColors.put("College Theater", c_default);
//		iconColors.put("Convenience Store", c_default);
//		iconColors.put("Mountain", c_default);
//		iconColors.put("Plane", c_default);
//		iconColors.put("Trade School", c_default);
//		iconColors.put("College Science Building", c_default);
//		iconColors.put("Laboratory", c_default);
//		iconColors.put("Track Stadium", c_default);
//		iconColors.put("Embassy / Consulate", c_default);
//		iconColors.put("Antique Shop", c_default);
//		iconColors.put("Community College", c_default);
//		iconColors.put("College Administrative Building", c_default);
//		iconColors.put("Bike Shop", c_default);
//		iconColors.put("Non-Profit", c_default);
//		iconColors.put("Taxi", c_default);
//		iconColors.put("Rest Area", c_default);
//		iconColors.put("Shrine", c_default);
//		iconColors.put("Tourist Information Center", c_default);
//		iconColors.put("Video Game Store", c_default);
//		iconColors.put("Paper / Office Supplies Store", c_default);
//		iconColors.put("Winery", c_default);
//		iconColors.put("Lingerie Store", c_default);
//		iconColors.put("College Track", c_default);
//		iconColors.put("Pet Store", c_default);
//		iconColors.put("Sorority House", c_default);
//		iconColors.put("College Engineering Building", c_default);
//		iconColors.put("College Quad", c_default);
//		iconColors.put("College Bookstore", c_default);
//		iconColors.put("College Football Field", c_default);
//		iconColors.put("Gift Shop", c_default);
//		iconColors.put("College Rec Center", c_default);
//		iconColors.put("College Soccer Field", c_default);
//		iconColors.put("Skating Rink", c_default);
//		iconColors.put("Spiritual Center", c_default);
//		iconColors.put("Wings Joint", c_default);
//		iconColors.put("Cajun / Creole Restaurant", c_default);
//		iconColors.put("Filipino Restaurant", c_default);
//		iconColors.put("Dim Sum Restaurant", c_default);
//		iconColors.put("Burrito Place", c_default);
//		iconColors.put("Salad Place", c_default);
//		iconColors.put("Food", c_default);
//		iconColors.put("Food Court", c_default);
//		iconColors.put("Seafood Restaurant", c_default);
//		iconColors.put("Juice Bar", c_default);
	}
	
	private void createCategoryParents(){
		categoryParents.put("Arts & Entertainment", "Arts & Entertainment");
		categoryParents.put("Aquarium", "Arts & Entertainment");
		categoryParents.put("Arcade", "Arts & Entertainment");
		categoryParents.put("Art Gallery", "Arts & Entertainment");
		categoryParents.put("Bowling Alley", "Arts & Entertainment");
		categoryParents.put("Casino", "Arts & Entertainment");
		categoryParents.put("Comedy Club", "Arts & Entertainment");
		categoryParents.put("Concert Hall", "Arts & Entertainment");
		categoryParents.put("General Entertainment", "Arts & Entertainment");
		categoryParents.put("Historic Site", "Arts & Entertainment");
		categoryParents.put("Movie Theater", "Arts & Entertainment");
		categoryParents.put("Indie Movie Theater", "Arts & Entertainment");
		categoryParents.put("Multiplex", "Arts & Entertainment");
		categoryParents.put("Museum", "Arts & Entertainment");
		categoryParents.put("Art Museum", "Arts & Entertainment");
		categoryParents.put("History Museum", "Arts & Entertainment");
		categoryParents.put("Planetarium", "Arts & Entertainment");
		categoryParents.put("Science Museum", "Arts & Entertainment");
		categoryParents.put("Music Venue", "Arts & Entertainment");
		categoryParents.put("Jazz Club", "Arts & Entertainment");
		categoryParents.put("Piano Bar", "Arts & Entertainment");
		categoryParents.put("Rock Club", "Arts & Entertainment");
		categoryParents.put("Performing Arts Venue", "Arts & Entertainment");
		categoryParents.put("Dance Studio", "Arts & Entertainment");
		categoryParents.put("Indie Theater", "Arts & Entertainment");
		categoryParents.put("Opera House", "Arts & Entertainment");
		categoryParents.put("Theater", "Arts & Entertainment");
		categoryParents.put("Pool Hall", "Arts & Entertainment");
		categoryParents.put("Public Art", "Arts & Entertainment");
		categoryParents.put("Racetrack", "Arts & Entertainment");
		categoryParents.put("Stadium", "Arts & Entertainment");
		categoryParents.put("Baseball Stadium", "Arts & Entertainment");
		categoryParents.put("Basketball Stadium", "Arts & Entertainment");
		categoryParents.put("Cricket Ground", "Arts & Entertainment");
		categoryParents.put("Football Stadium", "Arts & Entertainment");
		categoryParents.put("Hockey Arena", "Arts & Entertainment");
		categoryParents.put("Soccer Stadium", "Arts & Entertainment");
		categoryParents.put("Tennis", "Arts & Entertainment");
		categoryParents.put("Track Stadium", "Arts & Entertainment");
		categoryParents.put("Theme Park", "Arts & Entertainment");
		categoryParents.put("Water Park", "Arts & Entertainment");
		categoryParents.put("Zoo", "Arts & Entertainment");
		categoryParents.put("College & University", "College & University");
		categoryParents.put("College Academic Building", "College & University");
		categoryParents.put("College Arts Building", "College & University");
		categoryParents.put("College Communications Building", "College & University");
		categoryParents.put("College Engineering Building", "College & University");
		categoryParents.put("College History Building", "College & University");
		categoryParents.put("College Math Building", "College & University");
		categoryParents.put("College Science Building", "College & University");
		categoryParents.put("College Technology Building", "College & University");
		categoryParents.put("College Administrative Building", "College & University");
		categoryParents.put("College Auditorium", "College & University");
		categoryParents.put("College Bookstore", "College & University");
		categoryParents.put("College Cafeteria", "College & University");
		categoryParents.put("College Classroom", "College & University");
		categoryParents.put("College Gym", "College & University");
		categoryParents.put("College Lab", "College & University");
		categoryParents.put("College Library", "College & University");
		categoryParents.put("College Quad", "College & University");
		categoryParents.put("College Rec Center", "College & University");
		categoryParents.put("College Residence Hall", "College & University");
		categoryParents.put("College Stadium", "College & University");
		categoryParents.put("College Baseball Diamond", "College & University");
		categoryParents.put("College Basketball Court", "College & University");
		categoryParents.put("College Cricket Pitch", "College & University");
		categoryParents.put("College Football Field", "College & University");
		categoryParents.put("College Hockey Rink", "College & University");
		categoryParents.put("College Soccer Field", "College & University");
		categoryParents.put("College Tennis Court", "College & University");
		categoryParents.put("College Track", "College & University");
		categoryParents.put("College Theater", "College & University");
		categoryParents.put("Community College", "College & University");
		categoryParents.put("Fraternity House", "College & University");
		categoryParents.put("General College & University", "College & University");
		categoryParents.put("Law School", "College & University");
		categoryParents.put("Medical School", "College & University");
		categoryParents.put("Sorority House", "College & University");
		categoryParents.put("Student Center", "College & University");
		categoryParents.put("Trade School", "College & University");
		categoryParents.put("University", "College & University");
		categoryParents.put("Food", "Food");
		categoryParents.put("Afghan Restaurant", "Food");
		categoryParents.put("African Restaurant", "Food");
		categoryParents.put("American Restaurant", "Food");
		categoryParents.put("Arepa Restaurant", "Food");
		categoryParents.put("Argentinian Restaurant", "Food");
		categoryParents.put("Asian Restaurant", "Food");
		categoryParents.put("Australian Restaurant", "Food");
		categoryParents.put("BBQ Joint", "Food");
		categoryParents.put("Bagel Shop", "Food");
		categoryParents.put("Bakery", "Food");
		categoryParents.put("Brazilian Restaurant", "Food");
		categoryParents.put("Breakfast Spot", "Food");
		categoryParents.put("Brewery", "Food");
		categoryParents.put("Burger Joint", "Food");
		categoryParents.put("Burrito Place", "Food");
		categoryParents.put("Café", "Food");
		categoryParents.put("Cajun / Creole Restaurant", "Food");
		categoryParents.put("Caribbean Restaurant", "Food");
		categoryParents.put("Chinese Restaurant", "Food");
		categoryParents.put("Coffee Shop", "Food");
		categoryParents.put("Cuban Restaurant", "Food");
		categoryParents.put("Cupcake Shop", "Food");
		categoryParents.put("Deli / Bodega", "Food");
		categoryParents.put("Dessert Shop", "Food");
		categoryParents.put("Dim Sum Restaurant", "Food");
		categoryParents.put("Diner", "Food");
		categoryParents.put("Distillery", "Food");
		categoryParents.put("Donut Shop", "Food");
		categoryParents.put("Dumpling Restaurant", "Food");
		categoryParents.put("Eastern European Restaurant", "Food");
		categoryParents.put("Ethiopian Restaurant", "Food");
		categoryParents.put("Falafel Restaurant", "Food");
		categoryParents.put("Fast Food Restaurant", "Food");
		categoryParents.put("Filipino Restaurant", "Food");
		categoryParents.put("Fish & Chips Shop", "Food");
		categoryParents.put("Food Truck", "Food");
		categoryParents.put("French Restaurant", "Food");
		categoryParents.put("Fried Chicken Joint", "Food");
		categoryParents.put("Gastropub", "Food");
		categoryParents.put("German Restaurant", "Food");
		categoryParents.put("Gluten-free Restaurant", "Food");
		categoryParents.put("Greek Restaurant", "Food");
		categoryParents.put("Hot Dog Joint", "Food");
		categoryParents.put("Ice Cream Shop", "Food");
		categoryParents.put("Indian Restaurant", "Food");
		categoryParents.put("Indonesian Restaurant", "Food");
		categoryParents.put("Italian Restaurant", "Food");
		categoryParents.put("Japanese Restaurant", "Food");
		categoryParents.put("Juice Bar", "Food");
		categoryParents.put("Korean Restaurant", "Food");
		categoryParents.put("Latin American Restaurant", "Food");
		categoryParents.put("Mac & Cheese Joint", "Food");
		categoryParents.put("Malaysian Restaurant", "Food");
		categoryParents.put("Mediterranean Restaurant", "Food");
		categoryParents.put("Mexican Restaurant", "Food");
		categoryParents.put("Middle Eastern Restaurant", "Food");
		categoryParents.put("Molecular Gastronomy Restaurant", "Food");
		categoryParents.put("Mongolian Restaurant", "Food");
		categoryParents.put("Moroccan Restaurant", "Food");
		categoryParents.put("New American Restaurant", "Food");
		categoryParents.put("Peruvian Restaurant", "Food");
		categoryParents.put("Pizza Place", "Food");
		categoryParents.put("Portuguese Restaurant", "Food");
		categoryParents.put("Ramen /  Noodle House", "Food");
		categoryParents.put("Restaurant", "Food");
		categoryParents.put("Salad Place", "Food");
		categoryParents.put("Sandwich Place", "Food");
		categoryParents.put("Scandinavian Restaurant", "Food");
		categoryParents.put("Seafood Restaurant", "Food");
		categoryParents.put("Snack Place", "Food");
		categoryParents.put("Soup Place", "Food");
		categoryParents.put("South American Restaurant", "Food");
		categoryParents.put("Southern / Soul Food Restaurant", "Food");
		categoryParents.put("Spanish Restaurant", "Food");
		categoryParents.put("Paella Restaurant", "Food");
		categoryParents.put("Steakhouse", "Food");
		categoryParents.put("Sushi Restaurant", "Food");
		categoryParents.put("Swiss Restaurant", "Food");
		categoryParents.put("Taco Place", "Food");
		categoryParents.put("Tapas Restaurant", "Food");
		categoryParents.put("Tea Room", "Food");
		categoryParents.put("Thai Restaurant", "Food");
		categoryParents.put("Turkish Restaurant", "Food");
		categoryParents.put("Vegetarian / Vegan Restaurant", "Food");
		categoryParents.put("Vietnamese Restaurant", "Food");
		categoryParents.put("Winery", "Food");
		categoryParents.put("Wings Joint", "Food");
		categoryParents.put("Nightlife Spot", "Nightlife Spot");
		categoryParents.put("Bar", "Nightlife Spot");
		categoryParents.put("Beer Garden", "Nightlife Spot");
		categoryParents.put("Cocktail Bar", "Nightlife Spot");
		categoryParents.put("Dive Bar", "Nightlife Spot");
		categoryParents.put("Gay Bar", "Nightlife Spot");
		categoryParents.put("Hookah Bar", "Nightlife Spot");
		categoryParents.put("Hotel Bar", "Nightlife Spot");
		categoryParents.put("Karaoke Bar", "Nightlife Spot");
		categoryParents.put("Lounge", "Nightlife Spot");
		categoryParents.put("Nightclub", "Nightlife Spot");
		categoryParents.put("Other Nightlife", "Nightlife Spot");
		categoryParents.put("Pub", "Nightlife Spot");
		categoryParents.put("Sake Bar", "Nightlife Spot");
		categoryParents.put("Speakeasy", "Nightlife Spot");
		categoryParents.put("Sports Bar", "Nightlife Spot");
		categoryParents.put("Strip Club", "Nightlife Spot");
		categoryParents.put("Whisky Bar", "Nightlife Spot");
		categoryParents.put("Wine Bar", "Nightlife Spot");
		categoryParents.put("Outdoors & Recreation", "Outdoors & Recreation");
		categoryParents.put("Athletic & Sport", "Outdoors & Recreation");
		categoryParents.put("Baseball Field", "Outdoors & Recreation");
		categoryParents.put("Basketball Court", "Outdoors & Recreation");
		categoryParents.put("Golf Course", "Outdoors & Recreation");
		categoryParents.put("Hockey Field", "Outdoors & Recreation");
		categoryParents.put("Paintball Field", "Outdoors & Recreation");
		categoryParents.put("Skate Park", "Outdoors & Recreation");
		categoryParents.put("Skating Rink", "Outdoors & Recreation");
		categoryParents.put("Soccer Field", "Outdoors & Recreation");
		categoryParents.put("Tennis Court", "Outdoors & Recreation");
		categoryParents.put("Volleyball Court", "Outdoors & Recreation");
		categoryParents.put("Beach", "Outdoors & Recreation");
		categoryParents.put("Surf Spot", "Outdoors & Recreation");
		categoryParents.put("Bridge", "Outdoors & Recreation");
		categoryParents.put("Campground", "Outdoors & Recreation");
		categoryParents.put("Cemetery", "Outdoors & Recreation");
		categoryParents.put("Dog Run", "Outdoors & Recreation");
		categoryParents.put("Farm", "Outdoors & Recreation");
		categoryParents.put("Field", "Outdoors & Recreation");
		categoryParents.put("Garden", "Outdoors & Recreation");
		categoryParents.put("Harbor / Marina", "Outdoors & Recreation");
		categoryParents.put("Hiking Trail", "Outdoors & Recreation");
		categoryParents.put("Hot Spring", "Outdoors & Recreation");
		categoryParents.put("Lake", "Outdoors & Recreation");
		categoryParents.put("Lighthouse", "Outdoors & Recreation");
		categoryParents.put("Mountain", "Outdoors & Recreation");
		categoryParents.put("Neighborhood", "Outdoors & Recreation");
		categoryParents.put("Other Great Outdoors", "Outdoors & Recreation");
		categoryParents.put("Park", "Outdoors & Recreation");
		categoryParents.put("Playground", "Outdoors & Recreation");
		categoryParents.put("Plaza", "Outdoors & Recreation");
		categoryParents.put("Pool", "Outdoors & Recreation");
		categoryParents.put("River", "Outdoors & Recreation");
		categoryParents.put("Rock Climbing Spot", "Outdoors & Recreation");
		categoryParents.put("Scenic Lookout", "Outdoors & Recreation");
		categoryParents.put("Sculpture Garden", "Outdoors & Recreation");
		categoryParents.put("Ski Area", "Outdoors & Recreation");
		categoryParents.put("Apres Ski Bar", "Outdoors & Recreation");
		categoryParents.put("Ski Chairlift", "Outdoors & Recreation");
		categoryParents.put("Ski Chalet", "Outdoors & Recreation");
		categoryParents.put("Ski Lodge", "Outdoors & Recreation");
		categoryParents.put("Ski Trail", "Outdoors & Recreation");
		categoryParents.put("Stable", "Outdoors & Recreation");
		categoryParents.put("Vineyard", "Outdoors & Recreation");
		categoryParents.put("Volcano", "Outdoors & Recreation");
		categoryParents.put("Well", "Outdoors & Recreation");
		categoryParents.put("Professional & Other Places", "Professional & Other Places");
		categoryParents.put("Animal Shelter", "Professional & Other Places");
		categoryParents.put("Auditorium", "Professional & Other Places");
		categoryParents.put("Building", "Professional & Other Places");
		categoryParents.put("Convention Center", "Professional & Other Places");
		categoryParents.put("Meeting Room", "Professional & Other Places");
		categoryParents.put("Event Space", "Professional & Other Places");
		categoryParents.put("Factory", "Professional & Other Places");
		categoryParents.put("Fair", "Professional & Other Places");
		categoryParents.put("Funeral Home", "Professional & Other Places");
		categoryParents.put("Government Building", "Professional & Other Places");
		categoryParents.put("Capitol Building", "Professional & Other Places");
		categoryParents.put("City Hall", "Professional & Other Places");
		categoryParents.put("Courthouse", "Professional & Other Places");
		categoryParents.put("Fire Station", "Professional & Other Places");
		categoryParents.put("Monument / Landmark", "Professional & Other Places");
		categoryParents.put("Police Station", "Professional & Other Places");
		categoryParents.put("Library", "Professional & Other Places");
		categoryParents.put("Medical Center", "Professional & Other Places");
		categoryParents.put("Dentist's Office", "Professional & Other Places");
		categoryParents.put("Doctor's Office", "Professional & Other Places");
		categoryParents.put("Emergency Room", "Professional & Other Places");
		categoryParents.put("Hospital", "Professional & Other Places");
		categoryParents.put("Laboratory", "Professional & Other Places");
		categoryParents.put("Optical Shop", "Professional & Other Places");
		categoryParents.put("Veterinarian", "Professional & Other Places");
		categoryParents.put("Military Base", "Professional & Other Places");
		categoryParents.put("Non-Profit", "Professional & Other Places");
		categoryParents.put("Office", "Professional & Other Places");
		categoryParents.put("Cafeteria", "Professional & Other Places");
		categoryParents.put("Campaign Office", "Professional & Other Places");
		categoryParents.put("Conference Room", "Professional & Other Places");
		categoryParents.put("Coworking Space", "Professional & Other Places");
		categoryParents.put("Tech Startup", "Professional & Other Places");
		categoryParents.put("Parking", "Professional & Other Places");
		categoryParents.put("Post Office", "Professional & Other Places");
		categoryParents.put("Radio Station", "Professional & Other Places");
		categoryParents.put("School", "Professional & Other Places");
		categoryParents.put("Elementary School", "Professional & Other Places");
		categoryParents.put("High School", "Professional & Other Places");
		categoryParents.put("Middle School", "Professional & Other Places");
		categoryParents.put("Music School", "Professional & Other Places");
		categoryParents.put("Nursery School", "Professional & Other Places");
		categoryParents.put("Spiritual Center", "Professional & Other Places");
		categoryParents.put("Church", "Professional & Other Places");
		categoryParents.put("Mosque", "Professional & Other Places");
		categoryParents.put("Shrine", "Professional & Other Places");
		categoryParents.put("Synagogue", "Professional & Other Places");
		categoryParents.put("Temple", "Professional & Other Places");
		categoryParents.put("Voting Booth", "Professional & Other Places");
		categoryParents.put("Residence", "Residence");
		categoryParents.put("Assisted Living", "Residence");
		categoryParents.put("Home (private)", "Residence");
		categoryParents.put("Housing Development", "Residence");
		categoryParents.put("Residential Building (Apartment / Condo)", "Residence");
		categoryParents.put("Shop & Service", "Shop & Service");
		categoryParents.put("Antique Shop", "Shop & Service");
		categoryParents.put("Arts & Crafts Store", "Shop & Service");
		categoryParents.put("Automotive Shop", "Shop & Service");
		categoryParents.put("Bank", "Shop & Service");
		categoryParents.put("Bike Shop", "Shop & Service");
		categoryParents.put("Board Shop", "Shop & Service");
		categoryParents.put("Bookstore", "Shop & Service");
		categoryParents.put("Bridal Shop", "Shop & Service");
		categoryParents.put("Camera Store", "Shop & Service");
		categoryParents.put("Candy Store", "Shop & Service");
		categoryParents.put("Car Dealership", "Shop & Service");
		categoryParents.put("Car Wash", "Shop & Service");
		categoryParents.put("Clothing Store", "Shop & Service");
		categoryParents.put("Accessories Store", "Shop & Service");
		categoryParents.put("Boutique", "Shop & Service");
		categoryParents.put("Kids Store", "Shop & Service");
		categoryParents.put("Lingerie Store", "Shop & Service");
		categoryParents.put("Men's Store", "Shop & Service");
		categoryParents.put("Shoe Store", "Shop & Service");
		categoryParents.put("Women's Store", "Shop & Service");
		categoryParents.put("Convenience Store", "Shop & Service");
		categoryParents.put("Cosmetics Shop", "Shop & Service");
		categoryParents.put("Credit Union", "Shop & Service");
		categoryParents.put("Daycare", "Shop & Service");
		categoryParents.put("Department Store", "Shop & Service");
		categoryParents.put("Design Studio", "Shop & Service");
		categoryParents.put("Drugstore / Pharmacy", "Shop & Service");
		categoryParents.put("EV Charging Station", "Shop & Service");
		categoryParents.put("Electronics Store", "Shop & Service");
		categoryParents.put("Financial or Legal Service", "Shop & Service");
		categoryParents.put("Flea Market", "Shop & Service");
		categoryParents.put("Flower Shop", "Shop & Service");
		categoryParents.put("Food & Drink Shop", "Shop & Service");
		categoryParents.put("Butcher", "Shop & Service");
		categoryParents.put("Cheese Shop", "Shop & Service");
		categoryParents.put("Farmers Market", "Shop & Service");
		categoryParents.put("Fish Market", "Shop & Service");
		categoryParents.put("Food Court", "Shop & Service");
		categoryParents.put("Gourmet Shop", "Shop & Service");
		categoryParents.put("Grocery Store", "Shop & Service");
		categoryParents.put("Liquor Store", "Shop & Service");
		categoryParents.put("Wine Shop", "Shop & Service");
		categoryParents.put("Furniture / Home Store", "Shop & Service");
		categoryParents.put("Gaming Cafe", "Shop & Service");
		categoryParents.put("Garden Center", "Shop & Service");
		categoryParents.put("Gas Station / Garage", "Shop & Service");
		categoryParents.put("Gift Shop", "Shop & Service");
		categoryParents.put("Gym / Fitness Center", "Shop & Service");
		categoryParents.put("Climbing Gym", "Shop & Service");
		categoryParents.put("Gym Pool", "Shop & Service");
		categoryParents.put("Gym", "Shop & Service");
		categoryParents.put("Martial Arts Dojo", "Shop & Service");
		categoryParents.put("Track", "Shop & Service");
		categoryParents.put("Yoga Studio", "Shop & Service");
		categoryParents.put("Hardware Store", "Shop & Service");
		categoryParents.put("Hobby Shop", "Shop & Service");
		categoryParents.put("Internet Cafe", "Shop & Service");
		categoryParents.put("Jewelry Store", "Shop & Service");
		categoryParents.put("Laundry Service", "Shop & Service");
		categoryParents.put("Mall", "Shop & Service");
		categoryParents.put("Miscellaneous Shop", "Shop & Service");
		categoryParents.put("Mobile Phone Shop", "Shop & Service");
		categoryParents.put("Motorcycle Shop", "Shop & Service");
		categoryParents.put("Music Store", "Shop & Service");
		categoryParents.put("Nail Salon", "Shop & Service");
		categoryParents.put("Newsstand", "Shop & Service");
		categoryParents.put("Paper / Office Supplies Store", "Shop & Service");
		categoryParents.put("Pet Service", "Shop & Service");
		categoryParents.put("Pet Store", "Shop & Service");
		categoryParents.put("Photography Lab", "Shop & Service");
		categoryParents.put("Real Estate Office", "Shop & Service");
		categoryParents.put("Record Shop", "Shop & Service");
		categoryParents.put("Recycling Facility", "Shop & Service");
		categoryParents.put("Salon / Barbershop", "Shop & Service");
		categoryParents.put("Smoke Shop", "Shop & Service");
		categoryParents.put("Spa / Massage", "Shop & Service");
		categoryParents.put("Sporting Goods Shop", "Shop & Service");
		categoryParents.put("Storage Facility", "Shop & Service");
		categoryParents.put("Tailor Shop", "Shop & Service");
		categoryParents.put("Tanning Salon", "Shop & Service");
		categoryParents.put("Tattoo Parlor", "Shop & Service");
		categoryParents.put("Thrift / Vintage Store", "Shop & Service");
		categoryParents.put("Toy / Game Store", "Shop & Service");
		categoryParents.put("Travel Agency", "Shop & Service");
		categoryParents.put("Video Game Store", "Shop & Service");
		categoryParents.put("Video Store", "Shop & Service");
		categoryParents.put("Travel & Transport", "Travel & Transport");
		categoryParents.put("Airport", "Travel & Transport");
		categoryParents.put("Airport Food Court", "Travel & Transport");
		categoryParents.put("Airport Gate", "Travel & Transport");
		categoryParents.put("Airport Lounge", "Travel & Transport");
		categoryParents.put("Airport Terminal", "Travel & Transport");
		categoryParents.put("Airport Tram", "Travel & Transport");
		categoryParents.put("Plane", "Travel & Transport");
		categoryParents.put("Bike Rental / Bike Share", "Travel & Transport");
		categoryParents.put("Bus Station", "Travel & Transport");
		categoryParents.put("Bus Line", "Travel & Transport");
		categoryParents.put("Embassy / Consulate", "Travel & Transport");
		categoryParents.put("Ferry", "Travel & Transport");
		categoryParents.put("Boat or Ferry", "Travel & Transport");
		categoryParents.put("Pier", "Travel & Transport");
		categoryParents.put("General Travel", "Travel & Transport");
		categoryParents.put("Hotel", "Travel & Transport");
		categoryParents.put("Bed & Breakfast", "Travel & Transport");
		categoryParents.put("Boarding House", "Travel & Transport");
		categoryParents.put("Hostel", "Travel & Transport");
		categoryParents.put("Hotel Pool", "Travel & Transport");
		categoryParents.put("Motel", "Travel & Transport");
		categoryParents.put("Resort", "Travel & Transport");
		categoryParents.put("Roof Deck", "Travel & Transport");
		categoryParents.put("Light Rail", "Travel & Transport");
		categoryParents.put("Moving Target", "Travel & Transport");
		categoryParents.put("Rental Car Location", "Travel & Transport");
		categoryParents.put("Rest Area", "Travel & Transport");
		categoryParents.put("Road", "Travel & Transport");
		categoryParents.put("Subway", "Travel & Transport");
		categoryParents.put("Taxi", "Travel & Transport");
		categoryParents.put("Tourist Information Center", "Travel & Transport");
		categoryParents.put("Train Station", "Travel & Transport");
		categoryParents.put("Platform", "Travel & Transport");
		categoryParents.put("Train", "Travel & Transport");
		categoryParents.put("Travel Lounge", "Travel & Transport");
	}
}
